// src/components/Code.tsx
import { Show } from 'solid-js';

export type Props = {
	value: string;
	caption?: string;
	respectMargin?: boolean;
};

export const Code = ({ value, caption = '', respectMargin = false }: Props) => (
	<div class="mb-6">
		<div
			class={`shadow border border-black ${
				respectMargin ? '' : 'lg:-mx-4'
			} shadow-[6px_6px_0_#00000020]`}
		>
			<div class="whitespace-pre p-2 font-mono overflow-x-scroll">{value}</div>
		</div>
		<Show when={caption}>
			<div class="pt-4 text-center text-gray-800 dark:text-gray-100 text-sm italic font-serif">
				{caption}
			</div>
		</Show>
	</div>
);

// src/lib/components/Code.svelte
<script lang="ts">
	import Highlight from 'svelte-highlight';
	import typescript from 'svelte-highlight/languages/typescript';
	import theme from 'svelte-highlight/styles/stackoverflow-light';

	export let value: string;
	export let caption: string = '';
	export let language: any = typescript;
	export let respectMargin: boolean = false;
</script>

<svelte:head>
	{@html theme}
</svelte:head>

<div class="mb-6">
	<div class="shadow border border-black {respectMargin || 'lg:-mx-4'}">
		<Highlight {language} code={value} />
	</div>
	{#if caption}
		<div class="pt-4 text-center text-gray-800 dark:text-gray-100 text-sm italic font-serif">
			{caption}
		</div>
	{/if}
</div>

<style>
	.shadow {
		box-shadow: 6px 6px 0 #00000020;
	}
</style>
